# Generated by Django 2.2.3 on 2019-07-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='companyAdress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司地址'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='companyEmail',
            field=models.EmailField(default=1, max_length=254, verbose_name='邮箱地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='companyLink',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='companyLinkPhone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话/微信'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='basicmodel',
            name='logoPic',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo'),
        ),
    ]
