# Generated by Django 2.2.3 on 2019-07-23 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20190722_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('desc', models.TextField(max_length=200, verbose_name='新闻描述')),
                ('image', models.ImageField(upload_to='news/', verbose_name='新闻封面')),
                ('is_hot', models.BooleanField(default=True, verbose_name='是否展示')),
                ('time', models.CharField(max_length=100, verbose_name='新闻时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '新闻列表',
                'verbose_name_plural': '新闻列表',
            },
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='index',
            field=models.IntegerField(default=0, help_text='数字越小在越前面', verbose_name='轮播顺序'),
        ),
    ]
