# Generated by Django 2.2.3 on 2019-07-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20190723_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicmodel',
            name='is_open',
            field=models.BooleanField(default=False, help_text='系统只取开启的第一个条数据为准', verbose_name='是否开启'),
        ),
    ]
