# Generated by Django 2.2.3 on 2019-07-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_basicmodel_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='content',
            field=models.TextField(default=1, max_length=200, verbose_name='新闻主体内容'),
            preserve_default=False,
        ),
    ]
