# Generated by Django 2.2.3 on 2019-07-25 19:59

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20190725_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='goods_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
