# Generated by Django 2.2.3 on 2019-07-25 20:01

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_newsmodel_goods_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='goods_desc',
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
