# Generated by Django 2.2.3 on 2019-07-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20190725_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='content',
        ),
    ]
